name: E2E Auth0 - FastAPI Test

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    env:
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
      AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
      AUTH0_TEST_USERNAME: ${{ secrets.AUTH0_TEST_USERNAME }}
      AUTH0_TEST_PASSWORD: ${{ secrets.AUTH0_TEST_PASSWORD }}
      BACKEND_URL: http://localhost:8000

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest httpx python-dotenv

      - name: Start FastAPI backend
        run: |
          cd backend
          nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          sleep 5

      - name: Run E2E Auth0 test
        run: pytest -v -s test_auth_flow.py
